version: "3.8"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upload
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production

networks:
  monitoring:
    external: true
